# Generated by Django 5.0.7 on 2024-07-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_paus',
            new_name='guest_can_pause',
        ),
    ]
